services:
  - type: static
    name: 3d-credit-card
    env: static
    buildCommand: echo "No build needed for static site"
    staticPublishPath: .
    envVars:
      - key: NODE_VERSION
        value: 18.17.0 